Sync template
pavlovcik/pay.ubq.fi pull request #1
Opened 2024-02-17 18:34 UTC by Keyrxng

Resolves https://github.com/ubiquity/pay.ubq.fi/issues/166

2024-02-17 20:54 UTC, Keyrxng commented
everything resolved but haven't fully tested all of the functions

2024-02-18 04:35 UTC, pavlovcik commented
Thank for this! But you should have used @ubiquity/pay.ubq.fi as the merge target.

2024-02-18 04:44 UTC, pavlovcik requested changes
Looks great but I saw some words that I don't expect to have passed spell check. Did you make sure to run `cspell` as part of the `yarn format` and commit lint?

2024-02-18 04:44 UTC, pavlovcik commented on static/scripts/rewards/web3/wallet.ts
> +  const currentNetworkId = parseInt(String(web3provider.network.chainId), 16);
Seems suspicious.

2024-02-18 04:44 UTC, pavlovcik commented on static/scripts/rewards/web3/wallet.ts
> +      return null;
```suggestion

```

2024-02-18 04:44 UTC, pavlovcik commented on static/scripts/rewards/abis/nftRewardAbi.ts
> +/* eslint-disable sonarjs/no-duplicate-string */
What's this for?

2024-02-18 04:44 UTC, pavlovcik commented on static/scripts/audit-report/types/audit.d.ts
> +    : never;
There must be a simpler type for this?

2024-02-18 04:44 UTC, pavlovcik commented on .eslintrc
Seems unusual to me that these were formatted differently.

2024-02-18 05:11 UTC, pavlovcik commented on static/scripts/rewards/abis/nftRewardAbi.ts
> +/* eslint-disable sonarjs/no-duplicate-string */
I see. Redundant strings here.

2024-02-18 05:43 UTC, merged